name: provisions
description: "Transformez la gestion de vos achats d'atelier en un jeu d'enfant avec notre application mobile intuitive, générant des rapports Excel détaillés et offrant un tableau de bord pour une analyse fluide de vos fournisseurs."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  crypto: ^3.0.3
  file_saver: 0.3.1
  shared_preferences: ^2.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  path: ^1.0.0
  excel: ^4.0.0
  path_provider: ^2.0.0
  provider: ^6.0.0
  syncfusion_flutter_charts: ^31.0.0
  share_plus: ^12.0.0
  intl: 0.20.2
  pdf: ^3.10.4
  printing: ^5.12.0
  supabase_flutter: ^2.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/EKIBAM.jpg
  remove_alpha_ios: true
